In [1]:
from eruption_forecast import FeaturesBuilder

In [2]:
tremor_csv = r"D:\Projects\eruption-forecast\examples\output\forecast\VG.OJN.00.EHN\tremor\tremor.csv"
label_csv = r"D:\Projects\eruption-forecast\examples\output\labels\label_2025-01-01_2025-12-31_ws-2_wo-0.75_sr-100.0_dtf-2.csv"

In [3]:
features = FeaturesBuilder(
	tremor_csv = tremor_csv,
	label_csv = label_csv,
	verbose = True,
	debug = False
)

In [4]:
features.df_tremor

,dsar_f0-f1,dsar_f1-f2,dsar_f2-f3,dsar_f3-f4,rsam_f0,rsam_f1,rsam_f2,rsam_f3,rsam_f4
datetime,,,,,,,,,
2025-01-01 00:00:00,42.295169,11.567851,2.475762,0.454574,0.578896,0.393133,0.234020,0.201090,0.802178
2025-01-01 00:10:00,8.339877,10.230095,2.396320,0.585748,0.193408,0.473813,0.318773,0.280802,0.873074
2025-01-01 00:20:00,9.837610,11.795762,2.379836,0.586542,0.255615,0.487551,0.318261,0.280866,0.874947
2025-01-01 00:30:00,8.639998,12.336922,2.229046,0.612159,0.248093,0.483001,0.321814,0.317194,0.903412
2025-01-01 00:40:00,7.958638,11.133125,2.342420,0.569708,0.198425,0.474674,0.312228,0.280739,0.900274
...,...,...,...,...,...,...,...,...,...
2025-08-24 23:10:00,2.718700,33.650569,2.310831,0.327144,0.262476,0.568230,0.253366,0.240390,1.228104
2025-08-24 23:20:00,12.509193,19.529559,2.336220,0.320351,0.352692,0.459871,0.251428,0.233194,1.230238
2025-08-24 23:30:00,5.053995,28.170113,2.298092,0.326905,0.313338,0.520053,0.249408,0.237460,1.219803
2025-08-24 23:40:00,12.991641,12.728328,2.210997,0.335065,0.236748,0.410906,0.253157,0.250271,1.250918
2025-08-24 23:50:00,4.785427,26.635672,2.298367,0.327448,0.309154,0.524830,0.260723,0.241330,1.255358

In [5]:
features.df_label

                      id  is_erupted
datetime
2025-01-01 00:00:00    0           0
2025-01-01 12:00:00    1           0
2025-01-02 00:00:00    2           0
2025-01-02 12:00:00    3           0
2025-01-03 00:00:00    4           0
...                  ...         ...
2025-12-29 00:00:00  724           0
2025-12-29 12:00:00  725           0
2025-12-30 00:00:00  726           0
2025-12-30 12:00:00  727           0
2025-12-31 00:00:00  728           0

[729 rows x 2 columns]